//
//  LSBleGattServicesConstants.h
//  LifesenseBle
//
//  Created by lifesense on 14-8-1.
//  Copyright (c) 2014年 lifesense. All rights reserved.
//

//
//  LSBleGattService.h
//  LifesenseBle
//
//  Created by lifesense on 14-8-1.
//  Copyright (c) 2014年 lifesense. All rights reserved.
//

#ifndef LifesenseBle_LSBleGattServiceConstants_h
#define LifesenseBle_LSBleGattServiceConstants_h

#pragma mark - device information service uuid
enum
{
    GENERIC_ACCESS_SERVICE_UUID=0x1800,
    DEVICE_NAME_CHARACTER=0x2a00,
    DEVICEINFO_SERVICE_UUID=0x180a,
    DEVICE_MANUFACTURER_CHARACTER  = 0x2a29,
    DEVICE_MODEL_NUMBER_CHARACTER  = 0x2a24,
    DEVICE_SERIAL_NUMBER_CHARACTER =  0x2a25,
    DEVICE_SYSTEM_ID_CHARACTER = 0x2a23,
    DEVICE_HARDWARE_VERSION_CHARACTER = 0x2a27,
    DEVICE_SOFTWARE_VERSION_CHARACTER = 0x2a28,
    DEVICE_FIRMWARE_VERSION_CHARACTER =0x2a26,
};

#pragma mark - weight scale service uuid
enum
{
    WEIGHTSCALE_SERVICE_UUID =0x7802,
    WEIGHTSCALE_FEATURE_CHARACTER = 0x8a20,
    WEIGHTSCALE_MEASUREMENT_CHARACTER =0x8a21,
    WEIGHTSCALE_APPENDMEASURE_CHARACTER=0x8a22,
    WEIGHTSCALE_INTERMEDIATE_CHARACTER =0x8a23,
    FACTORY_MODE_SERVICE = 0x7806,
    FACTORY_MODE_CHARACTER= 0x8a60,
    GENERAL_WEIGHT_SCALE_SERVICE_UUID = 0x78a2,
};

#pragma mark - sphygmometer service uuid
enum{
    BLOODPRESSURE_COMMAND_START_SERVICE_UUID=0x78e9,
    BLOODPRESSURE_A3_SERVICE_UUID=0x7889,
    BLOODPRESSURE_SERVICE_UUID = 0x7809,
    BLOODPRESSURE_MEASUREMENT_CHARACTER = 0x8a91,
    BLOODPRESSURE_INTERMEDIATE_CHARACTER = 0x8a92,
    BLOODPRESSURE_FEATURE_CHARACTER= 0x8a90,
     BLOODPRESSURE_A3_PHILIPS_SERVICE_UUID=0x7899,
};

#pragma mark - pedometer service uuid
enum{
    PEDOMETER_SERVICE_UUID=0x7801,
    PEDOMETER_FEATURE_CHARACTER=0x8a10,
    PEDOMETER_MEASUREMENT_CHARACTER=0x8a11,
};

#pragma mark - A4 pedometer service uuid
enum{
    kWXServiceUUID=0xFEE7,
    kWXInputCharacteristicUUID=0xFEC7,
    kWXOutputCharacteristicUUID=0xFEC8,
    
    PEDOMETER_SERVICE_UUID_A4=0xA400,
    DEVICE_DOWNLOAD_CHARACTER_A4=0xA401,
    DEVICE_UPLOAD_CHARACTER_A4=0xA402,
};


#pragma mark - A5 pedometer service uuid
enum{
    
    PEDOMETER_SERVICE_UUID_A5=0xA500,
    PEDOMETER_INDICATE_CHARACTER_A5=0xA501,
    PEDOMETER_WRITE_CHARACTER_A5=0xA502,
};

#pragma mark - kitchen scale service uuid
enum{
    KITCHENSCALE_SERVICE_UUID = 0x780a,
    KITCHENSCALE_FEATURE_CHARACTER = 0x8aa0,
    KITCHENSCALE_MEASUREMENT_CHARACTER = 0x8aa1,
    KITCHENSCALE_INTERMEDIATE_CHARACTER = 0x8aa2,
};

#pragma mark - height scale service uuid
enum{
    HEIGHT_SERVICE_UUID = 0x7803,
    HEIGHT_MEASUREMNT_CHARACTER = 0x8a31,
    HEIGHT_INTERMEDIATE_CHARACTER = 0x8a32,
    HEIGHT_FEATURE_CHARACTER = 0x8a30,
};

#pragma mark - A3 Fat scale service uuid
enum{
    GENERIC_FAT_SCALE_SERVICE_UUID=0x78A2,
    FAT_SCALE_A3_SERVICE_UUID=0x7892,
    FAT_SCALE_A3_FEATURE_CHARACTER=0x8a20,
    FAT_SCALE_A3_MEASUREMENT_CHARACTER=0x8a24,
    FAT_SCALE_A3_APPENDMEASURE_CHARACTER=0x8a22,
    FAT_SCALE_A3_INTERMEDIATE_CHARACTER=0x8a23,
    FAT_SCALE_A3_SALTER_SERVICE_UUID=0x7882,
    FAT_SCALE_A3_PHILIPS_SERVICE_UUID=0x78D2,
};


#pragma mark - download user info and command
enum{
    DEVICE_DOWNLOAD_CHARACTER=0x8a81,
    DEVICE_UPLOAD_CHARACTER=0x8a82,
    CURRENT_TIME_COMMAND=0x01,
    UTC_COMMAND =0x02,
    USER_NAME_COMMAND=0x03,
    USER_MESSAGE_COMMAND =0x04,
    CURRENT_STATE_COMMAND= 0x05,
    TARGET_STATE_COMMAND =0x06,
    DAY_STATE_COMMAND = 0x07,
    WEEK_STATE_COMMAND =0x08,
    RESULT_COMMAND = 0x20,
    SIGNATURE_COMMAND =0x21,
    DISCONNECT_COMMAND=0x22,
    USER_INFO_COMMAND =0x81,
    USER_NUMBER_AND_NAME_COMMAND=0x83,
    UPDATE_USERINFO_COMMAND=0xc0,
    UPDATE_USERSET_COMMAND=0xc1,
    PASSWORD_COMMAND=0xa0,
    RANDOM_NUMBER_COMMAND=0xa1,
    DEVICE_NAME_COMMAND=0x09,
    COMFIRM_INFO_COMMAND=0x50,
    CLAIM_USERNUMBER_COMMAND=0x51,
    CLAIM_SET_INFORMATION_COMMAND=0x52,
    DELETE_PAIRED_COMMAND=0x53,
    VIBRATION_VOICE_COMMAND=0X54,
};


#endif

